"""
Property-based tests for message list integrity.

Properties verified:
  - Message list always valid after any sequence of operations
  - Role alternation: no consecutive same-role (except tool results)
  - Tool call / tool result pairing: every call has exactly one result
  - First message is system or user
  - All roles are valid
  - Tool results appear after their corresponding assistant message
"""

import pytest
from hypothesis import given, settings, HealthCheck, assume
from hypothesis import strategies as st

pytestmark = [pytest.mark.property]


# ============================================================================
# Strategies for generating well-formed and malformed messages
# ============================================================================

VALID_ROLES = ["system", "user", "assistant", "tool"]


def system_msg(content="You are helpful"):
    return {"role": "system", "content": content}


def user_msg(content="Hello"):
    return {"role": "user", "content": content}


def assistant_msg(content="Sure", tool_calls=None):
    msg = {"role": "assistant", "content": content}
    if tool_calls:
        msg["tool_calls"] = [
            {"id": cid, "function": {"name": f"fn_{i}", "arguments": "{}"}}
            for i, cid in enumerate(tool_calls)
        ]
        msg["content"] = None
    return msg


def tool_msg(call_id, content="done"):
    return {"role": "tool", "content": content, "tool_call_id": call_id}


@st.composite
def well_formed_conversation(draw):
    """Generate a well-formed conversation with proper structure."""
    msgs = []

    # Optional system message
    if draw(st.booleans()):
        msgs.append(system_msg(draw(st.text(min_size=1, max_size=50))))

    # User message (required as first non-system)
    msgs.append(user_msg(draw(st.text(min_size=1, max_size=50))))

    # Generate turns
    n_turns = draw(st.integers(0, 5))
    for _ in range(n_turns):
        # Assistant may or may not use tools
        use_tools = draw(st.booleans())
        if use_tools:
            n_calls = draw(st.integers(1, 3))
            call_ids = [f"call_{draw(st.uuids())}" for _ in range(n_calls)]
            msgs.append(assistant_msg(tool_calls=call_ids))
            for cid in call_ids:
                msgs.append(tool_msg(cid, draw(st.text(min_size=1, max_size=30))))
        else:
            msgs.append(assistant_msg(draw(st.text(min_size=1, max_size=50))))

        # Follow up with user message (unless last turn)
        if draw(st.booleans()):
            msgs.append(user_msg(draw(st.text(min_size=1, max_size=50))))

    return msgs


@st.composite
def random_message(draw):
    """Generate a random message (may be malformed)."""
    role = draw(st.sampled_from(VALID_ROLES + ["oracle", "moderator", ""]))
    msg = {"role": role, "content": draw(st.text(max_size=30))}
    if role == "tool":
        msg["tool_call_id"] = draw(st.text(min_size=1, max_size=20))
    if role == "assistant" and draw(st.booleans()):
        n = draw(st.integers(0, 3))
        msg["tool_calls"] = [
            {"id": f"tc_{i}", "function": {"name": "f", "arguments": "{}"}}
            for i in range(n)
        ]
    return msg


# ============================================================================
# Import the checker (from thrice or new-files)
# ============================================================================

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "thrice"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "new-files"))

from invariants.message_invariants import MessageInvariantChecker
from invariants.base import InvariantError


# ============================================================================
# Property: well-formed conversations pass all checks
# ============================================================================

@given(msgs=well_formed_conversation())
@settings(max_examples=200, deadline=None)
def test_well_formed_conversations_pass_all_checks(msgs):
    """Any well-formed conversation generated by our strategy must pass
    all message invariant safety checks."""
    err = MessageInvariantChecker.check_all(msgs)
    assert err is None, f"Well-formed conversation failed check: {err}"


# ============================================================================
# Property: valid roles are always accepted
# ============================================================================

@given(role=st.sampled_from(VALID_ROLES))
def test_valid_role_accepted(role):
    """Every valid role passes the role check."""
    msgs = [{"role": role, "content": "x"}]
    assert MessageInvariantChecker.check_valid_roles(msgs) is None


# ============================================================================
# Property: invalid roles are always rejected
# ============================================================================

@given(role=st.text(min_size=1, max_size=20).filter(lambda r: r not in VALID_ROLES))
@settings(max_examples=50)
def test_invalid_role_rejected(role):
    """Any role not in VALID_ROLES is caught."""
    msgs = [{"role": role, "content": "x"}]
    err = MessageInvariantChecker.check_valid_roles(msgs)
    assert err is not None
    assert err.invariant_name == "ValidRoles"


# ============================================================================
# Property: tool_call/result pairing
# ============================================================================

@given(n_calls=st.integers(1, 5))
def test_complete_tool_pairing_passes(n_calls):
    """When every tool call has exactly one result, pairing check passes."""
    call_ids = [f"call_{i}" for i in range(n_calls)]
    msgs = [
        system_msg(),
        user_msg(),
        assistant_msg(tool_calls=call_ids),
    ]
    for cid in call_ids:
        msgs.append(tool_msg(cid))

    assert MessageInvariantChecker.check_tool_call_result_pairing(msgs) is None
    assert MessageInvariantChecker.check_no_orphaned_results(msgs) is None


@given(n_calls=st.integers(2, 5), drop_idx=st.data())
def test_missing_tool_result_caught(n_calls, drop_idx):
    """Dropping any one tool result should be caught."""
    call_ids = [f"call_{i}" for i in range(n_calls)]
    idx_to_drop = drop_idx.draw(st.integers(0, n_calls - 1))

    msgs = [
        system_msg(),
        user_msg(),
        assistant_msg(tool_calls=call_ids),
    ]
    for i, cid in enumerate(call_ids):
        if i != idx_to_drop:
            msgs.append(tool_msg(cid))

    err = MessageInvariantChecker.check_tool_call_result_pairing(msgs)
    assert err is not None, f"Missing result for call_{idx_to_drop} not caught"


# ============================================================================
# Property: orphaned results detected
# ============================================================================

@given(orphan_id=st.text(min_size=1, max_size=20))
def test_orphaned_result_always_detected(orphan_id):
    """A tool result with no matching call is always detected."""
    msgs = [
        system_msg(),
        user_msg(),
        assistant_msg("No tools used"),
        tool_msg(orphan_id),
    ]
    err = MessageInvariantChecker.check_no_orphaned_results(msgs)
    assert err is not None
    assert err.invariant_name == "NoOrphanedResults"


# ============================================================================
# Property: first message validation
# ============================================================================

@given(first_role=st.sampled_from(["system", "user"]))
def test_valid_first_message_accepted(first_role):
    """system or user as first message is always accepted."""
    msgs = [{"role": first_role, "content": "x"}]
    assert MessageInvariantChecker.check_valid_first_message(msgs) is None


@given(first_role=st.sampled_from(["assistant", "tool"]))
def test_invalid_first_message_rejected(first_role):
    """assistant or tool as first message is always rejected."""
    msg = {"role": first_role, "content": "x"}
    if first_role == "tool":
        msg["tool_call_id"] = "tc_0"
    msgs = [msg]
    err = MessageInvariantChecker.check_valid_first_message(msgs)
    assert err is not None


# ============================================================================
# Property: tool result ordering
# ============================================================================

@given(n_calls=st.integers(1, 4))
def test_correctly_ordered_results_pass(n_calls):
    """Results after their call always pass ordering check."""
    call_ids = [f"call_{i}" for i in range(n_calls)]
    msgs = [
        system_msg(),
        user_msg(),
        assistant_msg(tool_calls=call_ids),
    ] + [tool_msg(cid) for cid in call_ids]

    assert MessageInvariantChecker.check_tool_result_ordering(msgs) is None


# ============================================================================
# Property: consecutive same-role warning
# ============================================================================

@given(n=st.integers(2, 5))
def test_consecutive_user_messages_warned(n):
    """N consecutive user messages produce warnings."""
    msgs = [system_msg()] + [user_msg(f"msg_{i}") for i in range(n)]
    warnings = MessageInvariantChecker.warn_consecutive_same_role(msgs)
    assert len(warnings) == n - 1  # n-1 adjacent pairs


@given(n=st.integers(2, 5))
def test_consecutive_tool_results_not_warned(n):
    """N consecutive tool results are normal (not warned)."""
    call_ids = [f"call_{i}" for i in range(n)]
    msgs = [
        system_msg(),
        user_msg(),
        assistant_msg(tool_calls=call_ids),
    ] + [tool_msg(cid) for cid in call_ids]

    warnings = MessageInvariantChecker.warn_consecutive_same_role(msgs)
    assert len(warnings) == 0
